app-name: "medlemskap-joark-lytter-q4"
ingresses:
  - "https://pensjon-institusjonsmelding-lytter-q4.dev.adeo.no"
srvuserpath: "serviceuser/data/dev/srvmedlemskapjoarklytter"
env:
  - name: "KAFKA_BOOTSTRAP_SERVERS"
    value: ""
  - name: "SCHEMA_REGISTRY_URL"
    value: ""
  - name: "SECURITY_TOKEN_SERVICE"
    value: ""
  - name: "INST_TOPIC"
    value: ""
  - name: "INST_GROUP"
    value: ""
  - name: "JOARK-URL"
    value: ""
